### ISSUE TITLE
Error on Starting Open Advisor

### ISSUE THREAD

**Issue by hemangshah36** [marketcalls/openadvisor#3]
@marketcalls 

Kindly advise whether any steps are missed. Why module apscheduler is not found on starting.

Getting error as under:

```
PS C:\openadvisor> python app.py
Traceback (most recent call last):
  File "C:\openadvisor\app.py", line 2, in <module>
    from extensions import db, mail, login_manager, limiter, bcrypt, start_scheduler  File "C:\openadvisor\extensions.py", line 7, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'
```

On further checking extensions.py, getting following error warnings.

Import "apscheduler.schedulers.background" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

Import "apscheduler.triggers.interval" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

On further checking training_predictions.py, getting following error warnings.

  File "C:\openadvisor\training_predictions.py", line 7, in <module>
    from catboost import CatBoostRegressor
ModuleNotFoundError: No module named 'catboost'

Import "catboost" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

Import "sklearn.model_selection" could not be resolved from sourcePylance[reportMissingModuleSource](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource)

Import "sklearn.metrics" could not be resolved from sourcePylance[reportMissingModuleSource](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource)

Import "tqdm" could not be resolved from sourcePylance[reportMissingModuleSource](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingModuleSource)

**Comment by marketcalls** [comment]
Ensure that you installed all the python libraries using

`pip install -r requirements.txt`

It looks like you haven't installed those models. Ensure you are using virtual environments.

**Comment by hemangshah36** [comment]
@marketcalls 

(venv) PS C:\openadvisor> dir


    Directory: C:\openadvisor


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        05/08/2024   1:07 PM                catboost_info
d-----        05/08/2024   1:15 PM                instance
d-----        05/08/2024   1:07 PM                Notebook
d-----        05/08/2024   1:07 PM                predictions
d-----        05/08/2024   1:07 PM                routes
d-----        05/08/2024   1:07 PM                static
d-----        05/08/2024   1:07 PM                templates
d-----        05/08/2024   1:07 PM                training
d-----        05/08/2024   1:09 PM                venv
d-----        05/08/2024   1:31 PM                __pycache__
-a----        05/08/2024   1:14 PM            921 .env
-a----        05/08/2024   1:07 PM            485 .gitignore
-a----        05/08/2024   1:07 PM            924 .sample.env
-a----        05/08/2024   1:07 PM           1393 app.py
-a----        05/08/2024   1:07 PM            580 config.py
-a----        05/08/2024   1:07 PM           5880 data_downloader.py
-a----        05/08/2024   1:45 PM           2884 extensions.py
-a----        05/08/2024   1:07 PM           1250 forms.py
-a----        05/08/2024   1:07 PM          35823 LICENSE
-a----        05/08/2024   1:07 PM            435 models.py
-a----        05/08/2024   1:07 PM           4031 portfolio.csv
-a----        05/08/2024   1:07 PM           9061 README.md
-a----        05/08/2024   1:07 PM           2178 requirements.txt
-a----        05/08/2024   1:07 PM          13499 training_predictions.py


(venv) PS C:\openadvisor> pip install -r requirements.txt
Requirement already satisfied: alembic==1.13.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 1)) (1.13.2)
Requirement already satisfied: bcrypt==4.1.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 2)) (4.1.3)
Requirement already satisfied: beautifulsoup4==4.12.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 3)) (4.12.3)
Requirement already satisfied: blinker==1.8.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 4)) (1.8.2)
Requirement already satisfied: certifi==2024.6.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 5)) (2024.6.2)
Requirement already satisfied: charset-normalizer==3.3.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: click==8.1.7 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 7)) (8.1.7)
Requirement already satisfied: colorama==0.4.6 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: Deprecated==1.2.14 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 9)) (1.2.14)
Requirement already satisfied: dnspython==2.6.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 10)) (2.6.1)
Requirement already satisfied: email_validator==2.2.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 11)) (2.2.0)
Requirement already satisfied: Flask==3.0.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 12)) (3.0.3)
Requirement already satisfied: Flask-Bcrypt==1.0.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 13)) (1.0.1)
Requirement already satisfied: Flask-Limiter==3.7.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 14)) (3.7.0)
Requirement already satisfied: Flask-Login==0.6.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 15)) (0.6.3)
Requirement already satisfied: Flask-Mail==0.10.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 16)) (0.10.0)
Requirement already satisfied: Flask-Migrate==4.0.7 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 17)) (4.0.7)
Requirement already satisfied: Flask-SQLAlchemy==3.1.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 18)) (3.1.1)
Requirement already satisfied: Flask-WTF==1.2.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 19)) (1.2.1)
Requirement already satisfied: frozendict==2.4.4 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 20)) (2.4.4)
Requirement already satisfied: greenlet==3.0.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 21)) (3.0.3)
Requirement already satisfied: html5lib==1.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 22)) (1.1)
Requirement already satisfied: idna==3.7 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 23)) (3.7)
Requirement already satisfied: importlib_resources==6.4.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 24)) (6.4.0)
Requirement already satisfied: itsdangerous==2.2.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 25)) (2.2.0)
Requirement already satisfied: Jinja2==3.1.4 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 26)) (3.1.4)
Requirement already satisfied: limits==3.13.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 27)) (3.13.0)
Requirement already satisfied: lxml==5.2.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 28)) (5.2.2)
Requirement already satisfied: Mako==1.3.5 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 29)) (1.3.5)
Requirement already satisfied: markdown-it-py==3.0.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 30)) (3.0.0)
Requirement already satisfied: MarkupSafe==2.1.5 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 31)) (2.1.5)
Requirement already satisfied: mdurl==0.1.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 32)) (0.1.2)
Requirement already satisfied: multitasking==0.0.11 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 33)) (0.0.11)
Requirement already satisfied: numpy==1.26.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 34)) (1.26.2)
Requirement already satisfied: ordered-set==4.1.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 35)) (4.1.0)
Requirement already satisfied: packaging==24.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 36)) (24.1)
Requirement already satisfied: pandas==2.2.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 37)) (2.2.2)
Requirement already satisfied: pandas_ta==0.3.14b0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 38)) (0.3.14b0)
Requirement already satisfied: peewee==3.17.5 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 39)) (3.17.5)
Requirement already satisfied: platformdirs==4.2.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 40)) (4.2.2)
Requirement already satisfied: plotly==5.22.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 41)) (5.22.0)
Requirement already satisfied: Pygments==2.18.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 42)) (2.18.0)
Requirement already satisfied: python-dateutil==2.9.0.post0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 43)) (2.9.0.post0)
Requirement already satisfied: python-dotenv==1.0.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 44)) (1.0.1)
Requirement already satisfied: pytz==2024.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 45)) (2024.1)
Requirement already satisfied: requests==2.32.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 46)) (2.32.3)
Requirement already satisfied: rich==13.7.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 47)) (13.7.1)
Requirement already satisfied: six==1.16.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 48)) (1.16.0)
Requirement already satisfied: soupsieve==2.5 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 49)) (2.5)
Requirement already satisfied: SQLAlchemy==2.0.31 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 50)) (2.0.31)
Requirement already satisfied: tenacity==8.4.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 51)) (8.4.2)
Requirement already satisfied: typing_extensions==4.12.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 52)) (4.12.2)
Requirement already satisfied: tzdata==2024.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 53)) (2024.1)
Requirement already satisfied: urllib3==2.2.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 54)) (2.2.2)
Requirement already satisfied: webencodings==0.5.1 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 55)) (0.5.1)
Requirement already satisfied: Werkzeug==3.0.3 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 56)) (3.0.3)
Requirement already satisfied: wrapt==1.16.0 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 57)) (1.16.0)
Requirement already satisfied: WTForms==3.1.2 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 58)) (3.1.2)
Requirement already satisfied: yfinance==0.2.40 in c:\openadvisor\venv\lib\site-packages (from -r requirements.txt (line 59)) (0.2.40)
(venv) PS C:\openadvisor>

**Comment by marketcalls** [comment]
Can you try now installing fresh and updated the requirements.txt file

**Comment by hemangshah36** [comment]
> Can you try now installing fresh and updated the requirements.txt file

@marketcalls 

Still getting errors.

(venv) PS C:\openadvisor> python app.py
Traceback (most recent call last):
  File "C:\openadvisor\app.py", line 2, in <module>
    from extensions import db, mail, login_manager, limiter, bcrypt, start_scheduler 
  File "C:\openadvisor\extensions.py", line 13, in <module>
    from training_predictions import train_all_models, make_all_predictions  # Import your training and prediction functions
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\openadvisor\training_predictions.py", line 4, in <module>
    import pandas_ta as ta
  File "C:\openadvisor\venv\Lib\site-packages\pandas_ta\__init__.py", line 7, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'
(venv) PS C:\openadvisor>

**Comment by marketcalls** [comment]
# Resolving ModuleNotFoundError for `pkg_resources`

The error you're encountering is because the `pkg_resources` module, which is part of the `setuptools` package, is not installed in your virtual environment. You can resolve this by installing `setuptools`.

## Steps to Resolve

1. **Activate your virtual environment if it's not already active:**

    ```bash
    venv\Scripts\activate
    ```

2. **Install `setuptools`:**

    ```bash
    pip install setuptools
    ```

After installing `setuptools`, you should be able to run your script without encountering the `ModuleNotFoundError`.

If you continue to face issues, ensure that all required packages are installed by checking your `requirements.txt` file (if you have one) and installing the packages:

```bash
pip install -r requirements.txt

# Resolving ModuleNotFoundError for `pkg_resources`

The error you're encountering is because the `pkg_resources` module, which is part of the `setuptools` package, is not installed in your virtual environment. You can resolve this by installing `setuptools`.

## Steps to Resolve

1. **Activate your virtual environment if it's not already active:**

    ```bash
    venv\Scripts\activate
    ```

2. **Install `setuptools`:**

    ```bash
    pip install setuptools
    ```

After installing `setuptools`, you should be able to run your script without encountering the `ModuleNotFoundError`.

If you continue to face issues, ensure that all required packages are installed by checking your `requirements.txt` file (if you have one) and installing the packages:

```bash
pip install -r requirements.txt

**Comment by hemangshah36** [comment]
@marketcalls 

I did some R & D and it seems like I have found the culprit.

`(venv) PS C:\openadvisor> pip install sklearn
Collecting sklearn
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.        
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) PS C:\openadvisor> `

**Comment by marketcalls** [comment]
Thanks for the quick research. I had updated the fresh requirements.txt file can you check it out.

**Comment by hemangshah36** [comment]
@marketcalls 

Now, we are having new issue.

Collecting matplotlib==3.9.1 (from -r requirements.txt (line 56))
  Downloading matplotlib-3.9.1.tar.gz (36.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.1/36.1 MB 32.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      + meson setup C:\Users\Administrator\AppData\Local\Temp\2\pip-install-kszbk031\matplotlib_213881b6cb664480bb44471c547f970f C:\Users\Administrator\AppData\Local\Temp\2\pip-install-kszbk031\matplotlib_213881b6cb664480bb44471c547f970f\.mesonpy-2noilepw -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\Administrator\AppData\Local\Temp\2\pip-install-kszbk031\matplotlib_213881b6cb664480bb44471c547f970f\.mesonpy-2noilepw\meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-kszbk031\matplotlib_213881b6cb664480bb44471c547f970f      Build dir: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-kszbk031\matplotlib_213881b6cb664480bb44471c547f970f\.mesonpy-2noilepw
      Build type: native build
      Program python3 found: YES
      Project name: matplotlib
      Project version: 3.9.1
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]   
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\Administrator\AppData\Local\Temp\2\pip-install-kszbk031\matplotlib_213881b6cb664480bb44471c547f970f\.mesonpy-2noilepw\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hemangshah36** [comment]
@marketcalls 

Finally, I figured out.

I updated requirements.txt
Line No: 56 as
matplotlib==3.8.4 

Basically, matplotlib==3.9.1 was not getting installed; tried many times.
However, immediately previous version got installed.

You may check this aspect in detail at your end before committing any changes.

@marketcalls Thanks for all your support and best wishes for further development of this wonderful tool.

![image](https://github.com/user-attachments/assets/ff2fca3e-ad59-45b1-8011-d20b763ef336)
